### ISSUE TITLE
This workspace shadows //third_party/jdk/...

### ISSUE THREAD

**Issue by jeremyje** [mzhaom/trunk#4]
I cloned bazel and this repository. It appears that I can't do a `bazel fetch //...` against this repository because it appears to shadow the `//third_party/jdk` from the `base_workspace`.

`ERROR: /home/jeremyje/development/trunk/tools/defaults/BUILD:13:1: no such target '//tools/jdk:GenClass_deploy.jar': target 'GenClass_deploy.jar' not declared in package 'tools/jdk' defined by /home/jeremyje/development/trunk/tools/jdk/BUILD and referenced by '//tools/defaults:genclass'.`

Also it's not clear how I use `trunk` workspace. I'm trying to use a separate workspace that utilize `trunk` and the `base_workspace` but it's not clear how to do that. Can you provide an example `WORKSPACE` file in the docs?

**Comment by alexweili** [comment]
This can be fixed by adding one line in BUILD file of the directory:
exports_files([
+++    "GenClass_deploy.jar",
    "JavaBuilder_deploy.jar",
    "SingleJar_deploy.jar",
])

**Comment by jeremyje** [comment]
Thanks, that fixes it.

I also figured out how to use this properly. You have to add this workspace to the ~/.bazelrc. I thought it was supposed to use workspace bindings.

**Comment by mzhaom** [comment]
The suggested change is now committed, welcome to just send pull request next time.
Thanks!
