### ISSUE TITLE
ERROR: No toolchain found for cpu 'armeabi-v7a'.

### ISSUE THREAD

**Issue by alexweili** [mzhaom/trunk#5]
I encountered this during build:
bazel build examples/...:all
.................
ERROR: No toolchain found for cpu 'armeabi-v7a'.

I am building on x86, why do I need arm?

**Comment by jeremyje** [comment]
Workaround: *Delete the tools/cpp directory.*

I think I know what happened here. The //tools/cpp/... directory was copied from an older version of https://github.com/google/bazel/tree/master/tools/cpp. The copy went out of date.

Not sure what this impacts and if there were any patches applied to it.

**Comment by alexweili** [comment]
Cool, I saw your other reply.

Can you show me how you configured this in .blazerc file?  I think that it is needed to compile this correctly.

**Comment by jeremyje** [comment]
What I've done so far is a bit screwed up.
1. I have a docker file with these run commands. Should work normally.

git clone --recursive https://github.com/google/bazel bazel \
  && cd bazel/ \
	&& ./compile.sh \
	&& ./output/bazel build //scripts:bazel-complete.bash \
  && cp bazel-bin/scripts/bazel-complete.bash /etc/bash_completion.d \
	&& echo export PATH="$PATH:${PWD}/output/" >> /etc/bash.bashrc \
  && ./output/bazel fetch //third_party/... //examples/... //src/...

git clone --recursive https://github.com/mzhaom/trunk.git bazel_trunk

2. Delete the tools/cpp from the trunk.
3. Create a new workspace where I'll put my code in. Copy the contents of the trunk/WORKSPACE into the new WORKSPACE file.
4. ~/.bazelrc should have the trunk workspace in the path. 
Mine looks like:

cat ~/.bazelrc
build --package_path %workspace%:/home/jeremyje/development/trunk:/home/jeremyje/development/bazel/base_workspace
fetch --package_path %workspace%:/home/jeremyje/development/trunk:/home/jeremyje/development/bazel/base_workspace
query --package_path %workspace%:/home/jeremyje/development/trunk:/home/jeremyje/development/bazel/base_workspace

**Comment by alexweili** [comment]
Thanks, this worked!

**Comment by mzhaom** [comment]
Thanks for the report and suggested fix! I integrated tools/cpp from bazel upstream, which should fix the issue now. The reason I kept another copy was I would like to extend the crosstool definition to cover other compilers like LRTE, which I'm working as another project.
